//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaHS.BLL
{
    using System;
    using System.Collections.Generic;

    public partial class Stednja
    {

        public Stednja(double glavnica, int rokOrocenja, string naziv, Klijent odabraniKlijent)
        {
            Status = 1;
            Glavnica = glavnica;
            RokOrocenja = rokOrocenja;
            Naziv = naziv;
            Zaposlenik = Zaposlenik.PrijavljeniZaposlenik;
            Klijent = odabraniKlijent;
            EKS = vratiEfektivnuKamatnuStopu();
            RKS = IzracunajKonformniKamatniracun();
            KonacanIznos = IzracunajGlavniIznosStednje();
            Kamate = VratiKamateStednje();

        }
        public int Id { get; set; }
        public int Status { get; set; }
        public double Glavnica { get; set; }
        public double KonacanIznos { get; set; }
        public Nullable<int> Vrsta_id { get; set; }
        public double Kamate { get; set; }
        public Nullable<int> Zaposlenik_id { get; set; }
        public Nullable<double> RKS { get; set; }
        public Nullable<int> Klijent_id { get; set; }
        public double EKS { get; set; }
        public int RokOrocenja { get; set; }
        public string Naziv { get; set; }

        public virtual Klijent Klijent { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }

        public double vratiEfektivnuKamatnuStopu()
        {
            if (this.RokOrocenja >= 6 && this.RokOrocenja < 12) return 0.07d;
            if (RokOrocenja >= 12 && RokOrocenja < 24) return 0.25f;
            if (RokOrocenja >= 24 && RokOrocenja < 36) return 0.55d;
            if (RokOrocenja >= 36 && RokOrocenja < 48) return 1d;
            if (RokOrocenja >= 48 && RokOrocenja < 60) return 1.20d;
            if (RokOrocenja == 60) return 1.45;
            if (RokOrocenja > 60) return 1.70;
            else return 0;
        }

        public double IzracunajDekurzivniKamatniFaktor()
        {
            return 1 + (EKS / 100);
        }

        public double IzracunajKonformniKamatniracun()
        {
            return Math.Round(Math.Pow(IzracunajDekurzivniKamatniFaktor(), (double)1 / 12), 7);
        }

        public double IzracunajGlavniIznosStednje()
        {
            return this.Glavnica * Math.Pow(IzracunajKonformniKamatniracun(), RokOrocenja);
        }

        public double VratiKamateStednje()
        {
            return IzracunajGlavniIznosStednje() - Glavnica;
        }
    }
}
