//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaHS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TekuciRacun
    {
        public string IBAN { get; set; }
        public double DopustenoPrekoracenje { get; set; }
        public double KamatePoPrekoracenju { get; set; }
    
        public virtual Racun Racun { get; set; }
    }
}
