//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaHS.BLL
{
    using BankaHS.DAL.Repositories;
    using System;
    using System.Collections.Generic;

    public partial class Tip_zaposlenika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tip_zaposlenika()
        {
            this.Zaposlenik = new HashSet<Zaposlenik>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaposlenik> Zaposlenik { get; set; }
        public static bool ProvjeriPrijavljenog(Zaposlenik zaposlenik)
        {
            return TipZaposlenikaRepository.Instance.ProvjeriTipZaposlenog(zaposlenik)
                .Naziv
                .Equals("Administrator") ? true : false;
        }
        public static Tip_zaposlenika TipAdmin()
        {
            return TipZaposlenikaRepository.Instance.TipZaposlenikaAdmin();
        }
        public static Tip_zaposlenika TipObican()
        {
            return TipZaposlenikaRepository.Instance.TipZaposlenikaObican();
        }
        public static List<Tip_zaposlenika> DohvatiSveTipoveZaposlenika()
        {
            return TipZaposlenikaRepository.Instance.DohvatiSveVrsteZaposlenih();
        }
    }
}
