//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaHS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcija
    {
        public int Id { get; set; }
        public System.DateTime DatumTransakcije { get; set; }
        public double Saldo { get; set; }
        public string SaljeID { get; set; }
        public string PrimaID { get; set; }
    
        public virtual Racun Racun { get; set; }
        public virtual Racun Racun1 { get; set; }
    }
}
